#!/bin/bash
for i in `cat /etc/domainusers | cut -d ":" -f1`
do
    if [ -e "/home/${i}/.tino/.etc/mem_enable" ]
    then
        /sbin/cagefs_enter_user $i /usr/bin/memcached -d -B ascii -m 64 -s /home/${i}/.tinocacheplugin/memcached.sock
    else
       echo "User $i not enable memcached"
    fi
done
